# Generated by Django 4.2 on 2026-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_product_old_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="custom",
            name="print_colors",
            field=models.CharField(
                choices=[
                    ("1", "1 color"),
                    ("2", "2 colors"),
                    ("3", "3 colors"),
                    ("4", "4 colors"),
                    ("5_plus", "5+ colors (CMYK/process)"),
                ],
                default="1",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="custom",
            name="printing_type",
            field=models.CharField(
                choices=[
                    ("screen_printing", "screen printing"),
                    ("dtf", "dtf"),
                    ("dtg", "dtg"),
                    ("sublimation", "sublimation"),
                    ("vinyl_heat_transfer", "vinyl heat transfer"),
                    ("embroidery", "embroidery"),
                ],
                default="screen_printing",
                max_length=100,
                null=True,
            ),
        ),
    ]
