# Generated by Django 4.2 on 2026-02-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0026_custom_print_colors_custom_printing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="custom",
            name="print_position",
            field=models.CharField(
                choices=[
                    ("front_center", "front center"),
                    ("front_left_chest", "front left chest"),
                    ("back_center", "back center"),
                    ("left_sleeve", "left sleeve"),
                    ("right_sleeve", "right sleeve"),
                    ("front_and_back", "front and back"),
                ],
                default="front_center",
                max_length=100,
                null=True,
            ),
        ),
    ]
