# Generated by Django 4.2 on 2026-02-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_custom_print_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="print_colors",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1 color"),
                    ("2", "2 colors"),
                    ("3", "3 colors"),
                    ("4", "4 colors"),
                    ("5_plus", "5+ colors (CMYK/process)"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="print_position",
            field=models.CharField(
                blank=True,
                choices=[
                    ("front_center", "front center"),
                    ("front_left_chest", "front left chest"),
                    ("back_center", "back center"),
                    ("left_sleeve", "left sleeve"),
                    ("right_sleeve", "right sleeve"),
                    ("front_and_back", "front and back"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="printing_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("screen_printing", "screen printing"),
                    ("dtf", "dtf"),
                    ("dtg", "dtg"),
                    ("sublimation", "sublimation"),
                    ("vinyl_heat_transfer", "vinyl heat transfer"),
                    ("embroidery", "embroidery"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
