# Generated by Django 4.2 on 2026-02-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_product_print_colors_product_print_position_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="print_colors",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="print_position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="printing_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="unit_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="PrintPricing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant_type",
                    models.CharField(
                        choices=[
                            ("printing_type", "printing type"),
                            ("print_colors", "print colors"),
                            ("print_position", "print position"),
                        ],
                        max_length=50,
                    ),
                ),
                ("option_value", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=100)),
                ("extra_price", models.FloatField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "unique_together": {("variant_type", "option_value")},
            },
        ),
    ]
